import { NextPage } from "next";
import Head from "next/head";
import { H1 } from "../components/headings";
import {
  CreateStudent,
  GetAllStudents,
  GetSingleStudent,
  StudentModel,
  UpdateStudent,
} from "../components/sections/students";

const Students: NextPage = () => {
  return (
    <>
      <Head>
        <title>Students | Cornerstone Developer Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <H1>Students</H1>
      <StudentModel />
      <GetAllStudents />
      <GetSingleStudent />
      <CreateStudent />
      <UpdateStudent />
    </>
  );
};

export default Students;
